---
# Main destroy playbook - refactored for production use
# Usage:
#   ansible-playbook destroy.yml -e env=dev
#   ansible-playbook destroy.yml -e env=dev -e dry_run=true
#   ansible-playbook destroy.yml -e env=prod -e force_cleanup=true

- name: WOPI EKS Infrastructure Destruction
  hosts: localhost
  gather_facts: true
  
  vars:
    operation: "destroy"
    env: "{{ environment | default('dev') }}"
    
  pre_tasks:
    - name: Validate required variables
      ansible.builtin.assert:
        that:
          - cluster_name is defined
          - aws_region is defined
        fail_msg: "Missing required variables. Check your vars files."
        success_msg: "All required variables present"
      tags: [always]

    - name: Display destruction information
      ansible.builtin.debug:
        msg: |
          ========================================
          ⚠️  INFRASTRUCTURE DESTRUCTION ⚠️
          ========================================
          Environment: {{ env }}
          Cluster: {{ cluster_name }}
          Region: {{ aws_region }}
          Mode: {{ 'DRY RUN' if dry_run | default(false) else '🔥 DESTRUCTIVE OPERATION 🔥' }}
          Workspace Cleanup: {{ 'YES' if cleanup_workspace | default(false) else 'NO' }}
          ========================================
      tags: [always]

    - name: Final confirmation for production
      ansible.builtin.pause:
        prompt: |
          
          🚨 DANGER: PRODUCTION DESTRUCTION 🚨
          
          You are about to PERMANENTLY DELETE:
          - EKS Cluster: {{ cluster_name }}
          - All associated resources
          - This action CANNOT be undone
          
          Environment: {{ env }}
          
          Type 'destroy-{{ cluster_name }}' to confirm, or Ctrl+C to abort
      register: destroy_confirmation
      when: 
        - env == 'prod'
        - not dry_run | default(false)
        - not skip_confirmation | default(false)
      tags: [always]

    - name: Validate production confirmation
      ansible.builtin.assert:
        that:
          - destroy_confirmation.user_input == 'destroy-' + cluster_name
        fail_msg: "Confirmation text did not match. Aborting."
      when: 
        - env == 'prod'
        - not dry_run | default(false)
        - not skip_confirmation | default(false)
      tags: [always]

  tasks:
    - name: Load environment-specific variables
      ansible.builtin.include_vars:
        dir: "vars/{{ env }}"
      tags: [always]

    - name: Load common variables
      ansible.builtin.include_vars:
        dir: "vars"
      tags: [always]

    - name: Setup Terraform environment
      ansible.builtin.include_tasks:
        file: tasks/terraform-common.yml
      tags: [terraform, setup]

    - name: Execute destruction
      ansible.builtin.include_tasks:
        file: tasks/terraform-destroy.yml
      tags: [terraform, destroy]

  post_tasks:
    - name: Destruction summary
      ansible.builtin.debug:
        msg: |
          ========================================
          Destruction Complete
          ========================================
          Cluster: {{ cluster_name }}
          Environment: {{ env }}
          Status: DESTROYED
          
          Resources removed:
          - EKS Cluster and nodes
          - Redis ElastiCache
          - Kubernetes resources
          - Security groups
          
          NOTE: External database (db-wopi) was NOT destroyed
          ========================================
      tags: [always]

  environment:
    HTTP_PROXY: "{{ None }}"
    HTTPS_PROXY: "{{ None }}"
    NO_PROXY: .olympus.gaia.kosmos,.tartarus.gaia.kosmos,.gaia.kosmos,.hylandcloud.com,.onbaseonline.com
    http_proxy: "{{ None }}"
    https_proxy: "{{ None }}"
    no_proxy: .olympus.gaia.kosmos,.tartarus.gaia.kosmos,.gaia.kosmos,.hylandcloud.com,.onbaseonline.com,.github.com