- name: AWS Deployment Automation
  hosts: localhost
  gather_facts: true

  tasks:
    - name: wopi Deployment Automation
      block:
        - name: Load variables
          tags: load-vars
          ansible.builtin.include_vars:
            dir: "{{ item }}"
          loop:
            - "vars"
    - name: Infrastructure as Code
      tags: terraform
      block:
        - name: Launch TF destroy tasks
          ansible.builtin.include_tasks:
            file: destroy.yml
  environment:
    # need both uppercase and lowercase proxy settings for different modules
    HTTP_PROXY: "{{ None }}"
    HTTPS_PROXY: "{{ None }}"
    NO_PROXY: .olympus.gaia.kosmos,.tartarus.gaia.kosmos,.gaia.kosmos,.hylandcloud.com,.onbaseonline.com
    http_proxy: "{{ None }}"
    https_proxy: "{{ None }}"
    no_proxy: .olympus.gaia.kosmos,.tartarus.gaia.kosmos,.gaia.kosmos,.hylandcloud.com,.onbaseonline.com,.github.com
